### ISSUE TITLE
[JOSS review] Licenses don't match

### ISSUE THREAD

**Issue by janfreyberg** [Saran-nns/sorn#23]
Hi there,

as part of the preliminary checks I was going through your License for this repo, and I can see two conflicting license files:
`LICENSE` and `LICENSE.md`, one of which as Apache 2.0, the other has MIT.

Could you please choose one, and ensure you only have one license file in the repository?

Thanks!

**Comment by Saran-nns** [comment]
Thank you @janfreyberg. I chose MIT and updated the repository.

**Comment by janfreyberg** [comment]
Thank you :)
