### ISSUE TITLE
[JOSS review] is the list of authors in the JOSS submission complete?

### ISSUE THREAD

**Issue by janfb** [Saran-nns/sorn#26]
Hi there, another question related to the review (https://github.com/openjournals/joss-reviews/issues/3545). 

this code is the basis for your master thesis research conducted at University of Osnabrück, correct? Then I was wondering whether there could be any other researches involved in the work underlying this package, e.g., thesis supervisors?

**Comment by Saran-nns** [comment]
Hi @janfb. The network was created as part of my master's thesis. The actual thesis can be found at [repo](https://github.com/Saran-nns/PySORN_0.1). However, the PyPI package is not part of my thesis. Also, I have informed my supervisor about a possible publication in the future, but have not received any feedback in the last years. However, I am happy to credit my supervisor as a co-author of this package. But I think it is not appropriate to act without his concern. I will follow your recommendation in this case.

**Comment by janfb** [comment]
Hi @Saran-nns okay, I think this is fine then. I just wanted to make sure the supervisor(s) were considered in this process. Thanks!
