### ISSUE TITLE
[JOSS review] suggestions and requests

### ISSUE THREAD

**Issue by janfb** [Saran-nns/sorn#35]
Hi @Saran-nns and sorry, it took me a while to get back to review. 

Installation and example usage is working now, great! 

I have some suggestions regarding the documentation: At the moment the README seems a bit cluttered to me. There is short high level description of SORN, then a set of figures and then the table of contents for the whole documentation. My suggestion would be to reduce this a bit: 

1. Give the high-level description of SORN at the beginning and a very simple description of the components of the SORN (illustrated with the schematic figure) and how to set up a SORN using your package. Remove the other figures as it is difficult to understand them in this context / they are too small. 
2. Give the installation instruction and just then a link to the full documentation at `readthedocs`. Or paste the full documentation in the README like Jan Freyberg suggested, also fine, but I would actually prefer the slim version with the link. 

Other remarks: 
### Writing
In the paper itself I would not give the installation instructions, they are online and very clear don't need to be repeated. Rather I would invest in explaining SORN in detail with equations, like you are doing now, but accompanied by some figures like the schematic in the README. It would also be great to add more explanatory text to the equations, or, if this is out of the scope of this paper, to refer the reader to the references where they can read the explanations. Overall, the paper should give the user all they need to understand and then use the package (given only basic knowledge of SORN). 

### References
For mentioning liquid state machines / echo state networks in summary I think it would be good to cite the initial work on this by Herbert Jaeger and Wolfgang Maass, e.g.
- "Adaptive nonlinear system identification with echo state networks." Advances in neural information processing systems 15 (2002): 609-616. or
- Jaeger, Herbert, Wolfgang Maass, and Jose Principe. "Special issue on echo state networks and liquid state machines." (2007).

### Tests
I think it would be great to add some documentation to the tests, e.g., inline comments about what the tests are doing and why / why not they should fail. 

Let me know what you think of these suggestions.

**Comment by Saran-nns** [comment]
Hi @janfb,

Thanks for the suggestions

I have updated the README as you suggest

### Writing
 - Install instructions are removed
 - Illustration of SORN reservoir in the figure is added to the paper
 - I have added two reference articles that describe SORN in detail
 
### References
- The proposed ESN/LSM articles are cited accordingly

### Tests
- Inline comments are added to each method in the module test.py

Just found that the figure was not rendered in the paper. I corrected it now and verified it through whedon preview [site](https://whedon.theoj.org/preview). 

Thank you again :)

Looking forward to your feedback and suggestions

**Comment by janfb** [comment]
Looks great now, thanks for taking into account my suggestions!
