### ISSUE TITLE
List > float comparison without array conversion.

### ISSUE THREAD

**Issue by Delwddrylliwr** [Saran-nns/sorn#8]
Execution of the example code from the package PyPi page in Jupyter produces the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-ca1e9c3769b4> in <module>()
     11 #1.3 To resume the simulation, load the matrices_dict from previous simulation;
     12 matrices_dict, Exc_activity, Inh_activity, Rec_activity, num_active_connections = RunSorn(phase='Plasticity', matrices=matrices_dict,
---> 13                                                                           time_steps=100).run_sorn(inputs)

/home/tom/.local/lib/python3.6/site-packages/sorn/sorn.py in run_sorn(self, inp)
    564 
    565             """ Fraction of active connections between E-E network"""
--> 566             frac_pos_active_conn.append((Wee[i] > 0.0).sum())
    567 
    568             """ Recurrent drive"""

TypeError: '>' not supported between instances of 'list' and 'float'`

---------------------------------------------------------------------------

Meanwhile, the source version of sorn/sorn/sorn.RunSorn contains this code at line 608:

`""" Fraction of active connections between E-E network"""
            frac_pos_active_conn.append((np.asarray(Wee[i]) > 0.0).sum())` 

Was different code compiled into the dist?

**Comment by Saran-nns** [comment]
Yes you are right. The dist is not updated with the source yet. I will compile the source with few more features in the next release. Thank you :)

**Comment by Delwddrylliwr** [comment]
That sounds great. 

Does the np.asarray need adding into the dist version too, or have I got something else wrong with my setup when I run the sample code?

**Comment by Saran-nns** [comment]
Yes, the np.asarray supposed to be in dist version. I will compile the current source and update the package

**Comment by Delwddrylliwr** [comment]
Excellent, thanks for that.

I'm really grateful that you've put all this work in and are making SORN functionality more available to others :D

**Comment by Saran-nns** [comment]
@Delwddrylliwr Issue resolved in the latest release 0.2.7. Thanks for reporting the bug :)
